import { MongodbAidRequestHistoryEventDBProxy } from 'src/server/adapters/mongodb/aid_request_history_event/db_proxy/MongodbAidRequestHistoryEventDBProxy';
import { AidRequestMarkedAsWorkingOnHistoryEventDBProxy } from 'src/server/entities/public/aid_request_history_event/subtypes/marked_as_working_on/AidRequestMarkedAsWorkingOnHistoryEventDBProxy';

export class MongodbAidRequestMarkedAsWorkingOnHistoryEventDBProxy
  extends MongodbAidRequestHistoryEventDBProxy
  implements AidRequestMarkedAsWorkingOnHistoryEventDBProxy {}
